New methods for books and borrow records
alan890104/go-clean-architecture pull request #1
Opened 2023-10-06 14:31 UTC by tinwech

- Add put and delete method to books endpoints to modify books by their IDs
- Add records endpoints for getting borrow records

2023-10-12 07:01 UTC, alan890104 requested changes

2023-10-12 07:01 UTC, alan890104 commented on domain/book.go
@tinwech You should check all of your interface provides default implementation in repositories. The project is currently not buildable.

Take `BookRepository` as example, `DeleteById(ctx context.Context, id string) error` should be added to `book_repository.go` with default functions.

```go
func (r *bookRepository) DeleteById(ctx context.Context, id string) error {
	return nil
}
```

2023-10-12 07:01 UTC, alan890104 commented on api/restful/openapi.yaml
For clearly view the api in openapi editor, please add tags to categorize them

2023-10-12 13:03 UTC, tinwech commented
Solved build issue and added tags to API doc.

2023-10-14 03:44 UTC, tinwech commented
- update API doc
- fix repository query bug
- finish implementation of book/record usecase and repository

@alan890104 pls help review the code, thanks!

2023-10-14 18:31 UTC, alan890104 requested changes

2023-10-14 18:31 UTC, alan890104 commented on api/restful/routes/book_route.go
> +	r.POST("/borrow", bookController.BorrowBook)
Have you tested your API after implementing? I notice some inconsistencies between the `book_route.go` file and the `openapi.yaml` specification. Please **ensure code consistency and adherence to the API spec**.

First and foremost, remember that an API should not be mistaken for a proxy to a database; it should distinctly reflect its intended purpose. Secondly, ensure that it adheres to the [RESTful standards](https://aws.amazon.com/tw/what-is/restful-api/). As an illustration, consider actions like 'borrow' and 'return,' which are modifications and, therefore, should be implemented as 'PUT' actions.

2023-10-14 18:31 UTC, alan890104 commented on usecase/record_usecase.go
> +		StartDate: time.Now().UTC().Format(dateFormat),
In this repository, we've initialized the time configuration in `bootstrap`. You might want to consider utilizing `time.Local` in place of UTC.

2023-10-14 18:31 UTC, alan890104 commented on usecase/record_usecase.go
> +	endDate := time.Now().UTC().Format(dateFormat)
Same as above

2023-10-15 03:41 UTC, tinwech commented on api/restful/routes/book_route.go
> +	r.POST("/borrow", bookController.BorrowBook)
I forgot to discuss the 'borrow' and 'return' actions with you in our last meeting. I modified their APIs to include both book ID and user ID. I am confused about the best API design as these actions modify the book resource and create or modify a record. Which of the following is the best practice in this case? The first design is currently in use.

1. `POST /books/borrow` (bookId and userId in the request body)
2. `PUT /books/borrow/{bookId}?userId={userId}`
3. `PUT /books/borrow/{bookId}` (userId will be included in the JWT payload, not implemented yet though)

BTW, the APIs were manually tested and worked well, should I write unit/integration tests?

2023-10-18 18:00 UTC, alan890104 commented on api/restful/routes/book_route.go
> +	r.POST("/borrow", bookController.BorrowBook)
If there is no payload (user ID will be parsed from the JWT payload), `PUT /books/borrow/{bookId}` would be a better option. A query string (i.e., the string after the question mark in the URL) represents a filter and may only appear for pagination in the `GET` method. (Ofcourse there are some exceptions)

2023-10-18 18:00 UTC, merged