Apply RBAC with `casbin` package for access control
alan890104/go-clean-architecture pull request #2
Opened 2023-10-24 13:02 UTC by peterxcli

use casbin to add authorize feature

The system is a library with 3 roles: Director, Librarian, and Visitor.
Everyone can find all the books in the library.
registered visitors can borrow books, return books, and view their own borrowing records.
librarians can update the information of books and have all the privileges of registered visitors.
The director has full access to the librarians and can delete books. Deleting a book is a soft delete, so it does not affect the borrowing record.

2023-10-24 13:10 UTC, alan890104 commented
Amazing bro. Please give me several days to review these changes.

2023-10-24 13:14 UTC, alan890104 commented
@peterxcli BTW, could you please add these scenarios into `README.md`?

> The system is a library with 3 roles: Director, Librarian, and Visitor.
Everyone can find all the books in the library.
registered visitors can borrow books, return books, and view their own borrowing records.
librarians can update the information of books and have all the privileges of registered visitors.
The director has full access to the librarians and can delete books. Deleting a book is a soft delete, so it does not affect the borrowing record.

2023-10-24 13:36 UTC, peterxcli commented
> @peterxcli BTW, could you please add these scenarios into `README.md`?
> 
> > The system is a library with 3 roles: Director, Librarian, and Visitor.
> > Everyone can find all the books in the library.
> > registered visitors can borrow books, return books, and view their own borrowing records.
> > librarians can update the information of books and have all the privileges of registered visitors.
> > The director has full access to the librarians and can delete books. Deleting a book is a soft delete, so it does not affect the borrowing record.

done

2023-10-24 18:03 UTC, alan890104 requested changes
Additionally, could you please test these APIs in `stage` mode? I believe there may be some path issues that need to be addressed.

2023-10-24 18:03 UTC, alan890104 commented on rbac/enforcer.go
> +	projectDir, err := projectRootDir.GetRootDirectory()
Why is it necessary to introduce this third-party package (which is not widely used) to address the path issue? Could you describe the reasons for its usage?

2023-10-24 18:15 UTC, peterxcli commented on rbac/enforcer.go
> +	projectDir, err := projectRootDir.GetRootDirectory()
This is for me to test why I can't read the casbin model and policy file initially when I ran `go test ./...`, I will removed it.
Thanks for the reminder!

2023-10-24 18:43 UTC, peterxcli commented
> I have refactored a little bit part in your code, especially routes. Additionally, could you please test these APIs in `stage` mode? I believe there may be some path issues that need to be addressed. (e.g. mount rbac policy to volume)

resolved the path issue by copying the casbin config into runtime stage, the api access for `stage` built container recover

<img width="509" alt="Screenshot 2023-10-25 at 2 39 54 AM" src="https://github.com/alan890104/go-clean-architecture/assets/54034701/ec9c2850-0c20-4a9a-b633-8b74db15b0e0">

2023-10-25 12:41 UTC, alan890104 requested changes

2023-10-25 12:41 UTC, alan890104 commented on docker/Dockerfile
> +# Copy the configuration files from the build stage to the runtime stage
This method works as well, but I prefer to follow another design principle: `app = image + config`.

We can mount `model.conf` and `policy.csv` using Docker Compose volumes, so that whenever we change the configuration files, we don't have to rebuild the image again.

2023-10-25 12:41 UTC, alan890104 commented on rbac/enforcer.go
> +	modelPath := filepath.Join("rbac", "model.conf")
This is now more elegant than it was previously :)

2023-10-25 12:54 UTC, peterxcli commented on docker/Dockerfile
> +# Copy the configuration files from the build stage to the runtime stage
I get it

2023-10-25 12:57 UTC, alan890104 commented on docker/docker-compose.stage.yaml
> +      - $PWD/rbac:/rbac:ro
maybe we can mount those configuration files instead of mounting whole folders?

2023-10-25 13:20 UTC, peterxcli commented on docker/docker-compose.stage.yaml
> +      - $PWD/rbac:/rbac:ro
ur right. thx

2023-10-25 14:40 UTC, alan890104 approved these changes
LGTM

2023-10-25 14:40 UTC, merged